import os

def build(bld):
    top = bld.srcnode.abspath()
    libsources = bld.path.ant_glob(['*.F90'])
    bld(
        features='fypp fc fcprogram testdriver',
        testfiles=['tests'],
        source=libsources,
        target='fxudriver',
        use=['fortyxima'],
        includes=[os.path.join(top, 'tools/fxunit')]
    )
