
def build(bld):
    libsources = bld.path.ant_glob(['*.F90'])
    bld(
        features='m4fpp fc fcprogram testdriver',
        testfiles=[ 'tests' ],
        source=libsources,
        target='fxudriver',
        use=[ 'fortyxima' ],
        includes='../tools/fxunit'
    )

